# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
    tags:
      - v*.*
    
  pull_request:
    branches: [ main ]

jobs:
  Compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
  Test:
    
    needs: Compile
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Get gradle permission.
        run: chmod +x gradlew
        
      - name: Test with Gradle
        run: ./gradlew test
        
      - uses: actions/upload-artifact@v2
        with:
          name: testReport
          path: build/reports
          
  Assemble:
  
    needs: Test
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Get gradle permission.
        run: chmod +x gradlew
        
      - name: Assemble with Gradle
        run: ./gradlew assemble
      
      - uses: actions/upload-artifact@v2
        with:
          name: assembleJAR
          path: build/libs/*.jar
          
  Release:
  
    needs: Assemble
    
    runs-on: ubuntu-latest
    
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: assembleJAR
        uses: actions/download-artifact@v2
        
      - name: print current working directory
        run: ls ./
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




